nombre = 'luisa fernanda guavita angel'
print('Uso del operador in:')
print('e' in nombre)
print('w' in nombre)
print()
print('Uso de la función "len": ')
print(len(nombre))
print()
print('Uso de método "Upper":')
print(nombre.upper())
print('Uso de método "Lower":')
print(nombre.lower())
print('Uso de método "title":')
print(nombre.title())
print()
print('Uso de método "count":')
print(nombre.count('i'))